export const regulations = [
  {
    bait_allowed: "no",
    id: "1-0",
    season: "OPEN ALL YEAR",
    waterbody: "Aster Lake",
    waterbody_detail: "5-19-9-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-1",
    season: "OPEN JULY 16 TO OCT. 31",
    waterbody: "Barnaby Lake",
    waterbody_detail: "32-4-3-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "1-2",
    season: "CLOSED ALL YEAR",
    waterbody: "",
    waterbody_detail: "Tributaries and outlet ",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "",
    },
  },
  {
    bait_allowed: "no",
    id: "1-3",
    season: "OPEN ALL YEAR",
    waterbody: "Bear Pond",
    waterbody_detail: "36-14-4-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 30 cm; \n0 ARGR",
    },
  },
  {
    bait_allowed: "no",
    id: "1-4",
    season: "OPEN ALL YEAR",
    waterbody: "Bearspaw Reservoir",
    waterbody_detail: "",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "3 fish",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "Other trout limit 1 \nunder 35 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "1-5",
    season: "OPEN ALL YEAR",
    waterbody: "Big Iron Lake",
    waterbody_detail: "1-15-4-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 30 cm; \n0 ARGR ",
    },
  },
  {
    bait_allowed: "no",
    id: "1-6",
    season: "OPEN ALL YEAR",
    waterbody: "Burns Lake",
    waterbody_detail: "17-19-7-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-7",
    season: "OPEN ALL YEAR",
    waterbody: "Burstall Lakes [Upper]",
    waterbody_detail: "16-21-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-8",
    season: "OPEN ALL YEAR",
    waterbody: "Carburn Park Pond",
    waterbody_detail: "NE-23-23-1-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "",
    },
  },
  {
    bait_allowed: "no",
    id: "1-9",
    season: "OPEN ALL YEAR",
    waterbody: "Carnarvon Lake",
    waterbody_detail: "30-16-6-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-10",
    season: "OPEN JULY 1 TO OCT. 31",
    waterbody: "Chester Lake",
    waterbody_detail: "26-21-10-W5; Includes tributaries \nand outlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "2 fish \nunder 30 \ncm",
      brook_trout: "",
      dolly_varden: "2 fish",
      trout_total: "",
    },
  },
  {
    bait_allowed: "no",
    id: "1-11",
    season: "OPEN ALL YEAR",
    waterbody: "Commonwealth Lake",
    waterbody_detail: "29-21-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-12",
    season: "OPEN ALL YEAR",
    waterbody: "Crowsnest Lake",
    waterbody_detail: "",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "3 fish",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "5 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-13",
    season: "OPEN JUNE 16 TO AUG. 31",
    waterbody: "",
    waterbody_detail: "Tributaries",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "2 fish",
      dolly_varden: "",
      trout_total: "Other trout 0",
    },
  },
  {
    bait_allowed: "no",
    id: "1-14",
    season: "OPEN SEPT. 1 TO OCT. 31",
    waterbody: "",
    waterbody_detail: "Tributaries",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "0 fish",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "0 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-15",
    season: "OPEN ALL YEAR",
    waterbody: "East Scarpe Lake",
    waterbody_detail: "13-3-3-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-16",
    season: "OPEN ALL YEAR",
    waterbody: "Fortress Lake",
    waterbody_detail: "6-22-9-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-17",
    season: "OPEN ALL YEAR",
    waterbody: "Galatea Lakes",
    waterbody_detail: "13-22-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-18",
    season: "OPEN ALL YEAR",
    waterbody: "Gap Lake",
    waterbody_detail: "SW 20-24-09-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "2 fish",
      dolly_varden: "",
      trout_total: "Other trout 0",
    },
  },
  {
    bait_allowed: "no",
    id: "1-19",
    season: "OPEN ALL YEAR",
    waterbody: "Ghost Reservoir",
    waterbody_detail: "",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "5 trout; 0 CTTR",
    },
  },
  {
    bait_allowed: "no",
    id: "1-20",
    season: "OPEN MAY 1 TO OCT. 31",
    waterbody: "Glenmore Reservoir",
    waterbody_detail: "",
    fish_limits: {
      walleye: "",
      northern_pike: "3 fish",
      yellow_perch: "15 \nfish",
      lake_trout: "",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "5 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-21",
    season: "OPEN ALL YEAR",
    waterbody: "Headwall Lakes",
    waterbody_detail: "19,30-21-9-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-22",
    season: "OPEN ALL YEAR",
    waterbody: "Hogarth Lakes",
    waterbody_detail: "21-21-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "1-23",
    season: "OPEN ALL YEAR",
    waterbody: "Invincible Lake",
    waterbody_detail: "5-20-9-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-24",
    season: "OPEN MAY 1 TO SEPT. 30",
    waterbody: "Kids Can Catch Pond",
    waterbody_detail: "13-24-1-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "0 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-25",
    season: "OPEN ALL YEAR",
    waterbody: "Lake Of The Horns",
    waterbody_detail: "11-17-7-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-26",
    season: "OPEN ALL YEAR",
    waterbody: "Lillian Lake",
    waterbody_detail: "13-22-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "1-27",
    season: "OPEN ALL YEAR",
    waterbody: "Loomis Lake",
    waterbody_detail: "21-17-7-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-0",
    season: "CLOSED ALL YEAR",
    waterbody: "Lower Kananaskis Lake",
    waterbody_detail:
      "35-19-9-W5; northwest bay-the \n" +
      "portion north of a line drawn from the \n" +
      "southernmost tip of the peninsula in \n" +
      "NE 11-20-9-W5 due west to the point \n" +
      "where the line intersects the shoreline \n" +
      "of the lake (the northwest bay)",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "",
    },
  },
  {
    bait_allowed: "no",
    id: "2-1",
    season: "OPEN ALL YEAR",
    waterbody: "",
    waterbody_detail: "35-19-9-W5; the remainder of the \nlake",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "over 50 \ncm",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-2",
    season: "OPEN ALL YEAR",
    waterbody: "Lys Lake",
    waterbody_detail: "26-3-3-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-3",
    season: "OPEN ALL YEAR",
    waterbody: "Maude Lake",
    waterbody_detail: "14-20-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-4",
    season: "OPEN ALL YEAR",
    waterbody: "Memorial Lakes",
    waterbody_detail: "6-23-9-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-5",
    season: "OPEN ALL YEAR",
    waterbody: "Mount Lorette Ponds",
    waterbody_detail: "19-23-8-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-6",
    season: "OPEN ALL YEAR",
    waterbody: "Mud Lake",
    waterbody_detail: "22-21-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-7",
    season: "OPEN ALL YEAR",
    waterbody: "Odlum Lake",
    waterbody_detail: "33-17-7-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-8",
    season: "OPEN ALL YEAR",
    waterbody: "Oldman Reservoir",
    waterbody_detail:
      "The Crowsnest River downstream \n" +
      "of the Cowley Bridge, the Castle \n" +
      "River downstream of Hwy. 3, and the \n" +
      "Oldman River downstream of Sec. \n" +
      "Rd. 510. The boundaries are fixed \n" +
      "regardless of water level fluctuations.",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "5 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-9",
    season: "OPEN ALL YEAR",
    waterbody: "Phillips Lake",
    waterbody_detail: "18-8-5-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-10",
    season: "OPEN JULY 1 TO OCT. 31",
    waterbody: "Picklejar Lakes",
    waterbody_detail: "16, 17-18-6-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "0 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-11",
    season: "OPEN ALL YEAR",
    waterbody: "Pine Coulee Reservoir",
    waterbody_detail: "",
    fish_limits: {
      walleye: "3 fish",
      northern_pike: "3 fish",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "5 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-12",
    season: "OPEN ALL YEAR",
    waterbody: "Quarry Lake",
    waterbody_detail: "29-24-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 50 cm; \n0 ARGR",
    },
  },
  {
    bait_allowed: "no",
    id: "2-13",
    season: "OPEN JULY 16 TO OCT. 31",
    waterbody: "Rainy Ridge Lake",
    waterbody_detail: "32-3-3-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "2-14",
    season: "CLOSED ALL YEAR",
    waterbody: "",
    waterbody_detail: "Tributaries and outlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "",
    },
  },
  {
    bait_allowed: "no",
    id: "2-15",
    season: "OPEN JULY 16 TO OCT. 31",
    waterbody: "Rawson Lake",
    waterbody_detail: "11-19-9-W5; Includes tributaries and \noutlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "0 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-16",
    season: "OPEN ALL YEAR",
    waterbody: "Ribbon Lake",
    waterbody_detail: "19-22-9-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-17",
    season: "OPEN JULY 1 TO OCT. 31",
    waterbody: "Rummel Lake",
    waterbody_detail: "3-22-10-W5; Includes tributaries and \noutlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "2-18",
    season: "OPEN ALL YEAR",
    waterbody: "Running Rain Lake",
    waterbody_detail: "7-18-7-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 under 30 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "2-19",
    season: "OPEN ALL YEAR",
    waterbody: "Shark Lake",
    waterbody_detail: "NW-1-22-11-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "2-20",
    season: "OPEN ALL YEAR",
    waterbody: "Smuts Lakes",
    waterbody_detail: "24-21-11-W5; Includes tributaries \nand outlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "2-21",
    season: "OPEN JULY 16 TO OCT. 31",
    waterbody: "Southfork Lake",
    waterbody_detail: "29-4-3-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "2-22",
    season: "CLOSED ALL YEAR",
    waterbody: "",
    waterbody_detail: "Tributaries and outlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "",
    },
  },
  {
    bait_allowed: "no",
    id: "2-23",
    season: "OPEN JULY 1 TO OCT. 31",
    waterbody: "Sparrow's Egg Lake",
    waterbody_detail: "6-20-8-W5; Includes tributaries and \noutlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 50 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "3-0",
    season: "OPEN ALL YEAR",
    waterbody: "Spray Lakes Reservoir",
    waterbody_detail: "",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "3 fish",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "5 trout (includes 3 \nLKTR)",
    },
  },
  {
    bait_allowed: "no",
    id: "3-1",
    season: "OPEN JULY 1 TO AUG. 31",
    waterbody: "",
    waterbody_detail: "Tributaries",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "5 over \n30 cm",
      cutthroat_trout: "over 35 \ncm",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-2",
    season: "OPEN SEPT. 1 TO OCT. 31",
    waterbody: "",
    waterbody_detail: "Tributaries",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "0 fish",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "0 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-3",
    season: "OPEN ALL YEAR",
    waterbody: "Stenton Lake",
    waterbody_detail: "35-25-10-W5; Includes tributaries \nand outlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "3-4",
    season: "OPEN ALL YEAR",
    waterbody: "Sunken Lake",
    waterbody_detail: "Champion Lake; 26-21-5-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 40 cm",
    },
  },
  {
    bait_allowed: "no",
    id: "3-5",
    season: "OPEN ALL YEAR",
    waterbody: "Talus Lake",
    waterbody_detail: "25-20-8-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-6",
    season: "OPEN ALL YEAR",
    waterbody: "Three Isle Lake",
    waterbody_detail: "23-19-10-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-7",
    season: "OPEN ALL YEAR",
    waterbody: "Tombstone Lakes",
    waterbody_detail: "13-20-8-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-8",
    season: "CLOSED ALL YEAR",
    waterbody: "Unnamed (Blairmore \nWater Supply Reservoir)",
    waterbody_detail: "34-7-4-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "",
    },
  },
  {
    bait_allowed: "no",
    id: "3-9",
    season: "OPEN JULY 16 TO MAY 31",
    waterbody: "Upper Kananaskis Lake",
    waterbody_detail:
      "The portion of the lake within 100m of \nRawson Creek inlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "over 50 \ncm",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-10",
    season: "OPEN ALL YEAR",
    waterbody: "",
    waterbody_detail: "The remainder of the lake",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "over 50 \ncm",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-11",
    season: "OPEN JULY 1 TO OCT. 31",
    waterbody: "Watridge Lake",
    waterbody_detail: "11-22-11-W5; Includes tributaries and \noutlet",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "0 trout",
    },
  },
  {
    bait_allowed: "no",
    id: "3-12",
    season: "OPEN ALL YEAR",
    waterbody: "Wedge Pond",
    waterbody_detail: "14-22-9-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "1 trout over 50 cm; \n0 ARGR",
    },
  },
  {
    bait_allowed: "no",
    id: "3-13",
    season: "OPEN ALL YEAR",
    waterbody: "Window Mountain Lake",
    waterbody_detail: "29-9-5-W5",
    fish_limits: {
      walleye: "",
      northern_pike: "",
      yellow_perch: "",
      lake_trout: "",
      mountain_whitefish: "",
      cutthroat_trout: "",
      brook_trout: "",
      dolly_varden: "",
      trout_total: "2 trout",
    },
  },
];
